interface City {
  id: number;
  name: string;
  capital: string;
}

export const cities: City[] = [
  { id: 1, name: "Lagos", capital: "Ikeja" },
  { id: 2, name: "Kano", capital: "Kano" },
  { id: 3, name: "Ibadan", capital: "Ibadan" },
  { id: 4, name: "Kaduna", capital: "Kaduna" },
  { id: 5, name: "Port Harcourt", capital: "Port Harcourt" },
  { id: 6, name: "Benin City", capital: "Benin City" },
  { id: 7, name: "Maiduguri", capital: "Maiduguri" },
  { id: 8, name: "Zaria", capital: "Kaduna" },
  { id: 9, name: "Aba", capital: "Umuahia" },
  { id: 10, name: "Jos", capital: "Jos" },
  { id: 11, name: "Ilorin", capital: "Ilorin" },
  { id: 12, name: "Oyo", capital: "Ibadan" },
  { id: 13, name: "Enugu", capital: "Enugu" },
  { id: 14, name: "Abeokuta", capital: "Abeokuta" },
  { id: 15, name: "Abuja", capital: "Abuja" },
  { id: 16, name: "Sokoto", capital: "Sokoto" },
  { id: 17, name: "Onitsha", capital: "Awka" },
  { id: 18, name: "Warri", capital: "Asaba" },
  { id: 19, name: "Calabar", capital: "Calabar" },
  { id: 20, name: "Uyo", capital: "Uyo" },
  { id: 21, name: "Owerri", capital: "Owerri" },
  { id: 22, name: "Ikeja", capital: "Ikeja" },
  { id: 23, name: "Akure", capital: "Akure" },
  { id: 24, name: "Bauchi", capital: "Bauchi" },
  { id: 25, name: "Ife", capital: "Osogbo" },
  { id: 26, name: "Makurdi", capital: "Makurdi" },
  { id: 27, name: "Minna", capital: "Minna" },
  { id: 28, name: "Effon Alaiye", capital: "Ado-Ekiti" },
  { id: 29, name: "Ilesa", capital: "Osogbo" },
  { id: 30, name: "Oshogbo", capital: "Osogbo" },
  { id: 31, name: "Ondo", capital: "Akure" },
  { id: 32, name: "Damaturu", capital: "Damaturu" },
  { id: 33, name: "Jimeta", capital: "Yola" },
  { id: 34, name: "Ikot Ekpene", capital: "Uyo" },
  { id: 35, name: "Gombe", capital: "Gombe" },
  { id: 36, name: "Gusau", capital: "Gusau" },
  { id: 37, name: "Mubi", capital: "Yola" },
  { id: 38, name: "Nnewi", capital: "Awka" },
  { id: 39, name: "Ise-Ekiti", capital: "Ado-Ekiti" },
  { id: 40, name: "Katsina", capital: "Katsina" },
  { id: 41, name: "Lafia", capital: "Lafia" },
  { id: 42, name: "Okene", capital: "Lokoja" },
  { id: 43, name: "Gboko", capital: "Makurdi" },
  { id: 44, name: "Awka", capital: "Awka" },
  { id: 45, name: "Ijebu Ode", capital: "Abeokuta" },
  { id: 46, name: "Asaba", capital: "Asaba" },
  { id: 47, name: "Yenagoa", capital: "Yenagoa" },
  { id: 48, name: "Abakaliki", capital: "Abakaliki" },
  { id: 49, name: "Umuahia", capital: "Umuahia" },
  { id: 50, name: "Jalingo", capital: "Jalingo" },
];
