export const industries = [
  { id: 1, name: "Agriculture" },
  { id: 2, name: "Automotive" },
  { id: 3, name: "Banking" },
  { id: 4, name: "Construction" },
  { id: 5, name: "Education" },
  { id: 6, name: "Energy" },
  { id: 7, name: "Entertainment" },
  { id: 8, name: "Finance" },
  { id: 9, name: "Healthcare" },
  { id: 10, name: "Hospitality" },
  { id: 11, name: "Information Technology" },
  { id: 12, name: "Manufacturing" },
  { id: 13, name: "Media" },
  { id: 14, name: "Real Estate" },
  { id: 15, name: "Retail" },
  { id: 16, name: "Telecommunications" },
  { id: 17, name: "Transportation" },
  { id: 18, name: "Utilities" },
];
