export const organizations = [
  {
    id: 1,
    name: "Acme Corporation",
    website: "www.acme.com",
    city: "New York",
    size: "500+",
    industry: "Technology",
    verified: "Yes",
  },
  {
    id: 2,
    name: "Globex Corporation",
    website: "www.globex.com",
    city: "Springfield",
    size: "1000+",
    industry: "Manufacturing",
    verified: "No",
  },
  {
    id: 3,
    name: "Initech",
    website: "www.initech.com",
    city: "Austin",
    size: "250-500",
    industry: "Software",
    verified: "Yes",
  },
  {
    id: 4,
    name: "Wayne Enterprises",
    website: "www.wayneenterprises.com",
    city: "Gotham",
    size: "5000+",
    industry: "Conglomerate",
    verified: "Yes",
  },
  {
    id: 5,
    name: "Stark Industries",
    website: "www.starkindustries.com",
    city: "Los Angeles",
    size: "1000+",
    industry: "Technology",
    verified: "Yes",
  },
  {
    id: 6,
    name: "Umbrella Corporation",
    website: "www.umbrellacorp.com",
    city: "Raccoon City",
    size: "2000+",
    industry: "Pharmaceuticals",
    verified: "No",
  },
];
